Repository dialogic-godot/dialogic, pull requests merged in 2021-11, with the labels that each got.

#612 Fixing bug that prevented portrait update
  addons/dialogic/Nodes/DialogNode.gd
Labels: Bug 🐞

#614 Fixing wrong id for CTRL + T
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
Labels: Bug 🐞

#615 Fixing empty display name bug
  addons/dialogic/Parser/DialogicParser.gd
Labels: Bug 🐞

#613 Changing the DocsMarkdownParser to understand ``` code as well
  addons/dialogic/Documentation/Nodes/DocsMarkdownParser.gd
Labels: Documentation 📚

#607 fix code insertion in faq->Using Signals?
  addons/dialogic/Documentation/Content/FAQ/Signals.md
Labels: Documentation 📚

#622 Documentation improvements.
  addons/dialogic/Documentation/Content/FAQ/CSharp.md
  addons/dialogic/Documentation/Content/FAQ/Portraits.md
  addons/dialogic/Documentation/Content/FAQ/can-i-use-dialogic-in-my-project.md
  addons/dialogic/Documentation/Content/FAQ/create-timeline-using-gdscript.md
  addons/dialogic/Documentation/Content/FAQ/how-to-make-dialog-show-up-in-game.md
  addons/dialogic/Documentation/Content/FAQ/plugin-shipped-godot.md
  addons/dialogic/Documentation/Content/FAQ/resolution-small-dialog-big.md
  addons/dialogic/Documentation/Content/FAQ/why-not-graph-nodes.md
  addons/dialogic/Documentation/Content/Reference/001.md
  addons/dialogic/Documentation/Nodes/DocsTreeHelper.gd
  addons/dialogic/Other/DialogicClass.gd
Labels: Documentation 📚

#627 Fix crash when using Scene as Background
  addons/dialogic/Nodes/Background.gd
  addons/dialogic/Nodes/DialogNode.gd
Labels: Bug 🐞

#628 Fix broken TextBubble
  addons/dialogic/Nodes/TextBubble.tscn
Labels: Bug 🐞

#629 Small improvements
  addons/dialogic/Editor/EditorView.tscn
  addons/dialogic/Editor/MasterTree/MasterTree.gd
  addons/dialogic/Editor/ThemeEditor/AudioPicker.gd
  addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
  addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
  addons/dialogic/Nodes/DialogicCustomEvents.gd
Labels: Improvement✨, UI/UX ✏

#631 Fixing BBCode and command indexing
  addons/dialogic/Nodes/TextBubble.gd
Labels: Bug 🐞

#656 Mode that doesn't stretch the background
  addons/dialogic/Editor/SettingsEditor/SettingsEditor.tscn
  addons/dialogic/Nodes/Background.gd
Labels: Improvement✨
