Repository dialogic-godot/dialogic, pull requests merged in 2022-07, with the labels that each got.

#973 2.0 Allow escaping \comma in word selector text modifier
  addons/dialogic/Display/DialogText.gd
Labels: Feature✨

#974 2.0 Make sure text effect parser ignores`\[`
  addons/dialogic/Display/DialogText.gd
  addons/dialogic/Other/DialogicGameHandler.gd
Labels: Feature✨

#975 2.0 Implement Subsystems for code/logic separation
  addons/dialogic/Display/ChoiceButton.gd
  addons/dialogic/Display/DialogText.gd
  addons/dialogic/Events/Background/Subsystem_Backgrounds.gd
  addons/dialogic/Events/Background/event.gd
  addons/dialogic/Events/Background/icon.png
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Choice/Subsystem_Choices.gd
  addons/dialogic/Events/Choice/event.gd
  addons/dialogic/Events/Condition/event.gd
  addons/dialogic/Events/End Branch/event.gd
  addons/dialogic/Events/End/event.gd
  addons/dialogic/Events/Jump/event.gd
  addons/dialogic/Events/Music/Subsystem_Audio.gd
  addons/dialogic/Events/Music/event.gd
  addons/dialogic/Events/Signal/event.gd
  addons/dialogic/Events/Sound/event.gd
  addons/dialogic/Events/Text/Subsystem_Text.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Events/Theme/Subsystem_Themes.gd
  addons/dialogic/Events/Theme/event.gd
  addons/dialogic/Events/Theme/icon.png
  addons/dialogic/Events/Variable/event.gd
  addons/dialogic/Events/Wait/event.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/Dialogic_Subsystem.gd
  addons/dialogic/Other/TestTimelineScene.gd
  addons/dialogic/Resources/event.gd
  addons/dialogic/plugin.gd
  timelines/testy.dtl
Labels: Feature✨

#976 2.0 Allow dynamic input fields on dialog node
  addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd
  addons/dialogic/Editor/Events/Templates/EventNode.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Choice/event.gd
  addons/dialogic/Events/Music/event.gd
  addons/dialogic/Events/Sound/event.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏

#998 2.0 Add Character Animation support
  addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd
  addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.tscn
  addons/dialogic/Editor/Events/Templates/EventNode.gd
  addons/dialogic/Events/Character/AnimationsSettings.gd
  addons/dialogic/Events/Character/AnimationsSettings.tscn
  addons/dialogic/Events/Character/DefaultAnimations/bounce_in.gd
  addons/dialogic/Events/Character/DefaultAnimations/bounce_out.gd
  addons/dialogic/Events/Character/DefaultAnimations/fade_in_up.gd
  addons/dialogic/Events/Character/DefaultAnimations/fade_out_down.gd
  addons/dialogic/Events/Character/DefaultAnimations/heartbeat.gd
  addons/dialogic/Events/Character/DefaultAnimations/instant_in_or_out.gd
  addons/dialogic/Events/Character/DefaultAnimations/tada.gd
  addons/dialogic/Events/Character/DialogicAnimationClass.gd
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Jump/event.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Other/DialogicUtil.gd
  addons/dialogic/Resources/event.gd
  timelines/testy.dtl
Labels: Feature✨

#995 1.4.x Translation Service Speed Fixes
  addons/dialogic/Documentation/Content/Changelog.md
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
  addons/dialogic/Editor/CharacterEditor/PortraitEntry.gd
  addons/dialogic/Editor/Common/SectionTitle.gd
  addons/dialogic/Editor/Common/TLabel.gd
  addons/dialogic/Editor/EditorView.gd
  addons/dialogic/Editor/Events/Parts/Logic/EventPart_SetValuePicker.gd
  addons/dialogic/Editor/Events/Templates/EventBlock.gd
  addons/dialogic/Editor/MasterTree/MasterTree.gd
  addons/dialogic/Editor/SettingsEditor/Scenes/SettingsCheckbox.gd
  addons/dialogic/Editor/ThemeEditor/AudioPicker.gd
  addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
  addons/dialogic/Editor/TimelineEditor/SmallEventButton.gd
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
  addons/dialogic/Localization/dialogic.de.translation
  addons/dialogic/Localization/dialogic.en.translation
  addons/dialogic/Localization/dialogic.es.translation
  addons/dialogic/Localization/dialogic.fr.translation
  addons/dialogic/Localization/dialogic.zh_CN.translation
  addons/dialogic/Localization/translation_service.gd
Labels: Feature✨

#1016 2.0 Fix for dropping choice/condition
  addons/dialogic/Editor/Events/EventNode/EventNode.tscn
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
Labels: Bug 🐞

#1020 2.0 Character typing sound moods + Character extensions
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn
  addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd
  addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.tscn
  addons/dialogic/Editor/Settings/SettingsEditor.gd
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Choice/event.gd
  addons/dialogic/Events/Music/event.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.tscn
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds_MoodItem.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds_MoodItem.tscn
  addons/dialogic/Events/Text/DialogicDisplay_TypeSounds.gd
  addons/dialogic/Events/Text/Display_DialogText.gd
  addons/dialogic/Events/Text/Subsystem_Text.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Events/Theme/Theme_CharacterEdit.gd
  addons/dialogic/Events/Theme/Theme_CharacterEdit.tscn
  addons/dialogic/Events/Theme/event.gd
  addons/dialogic/Events/Variable/event.gd
  addons/dialogic/Other/DefaultDialogNode.tscn
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
  addons/dialogic/Resources/character.gd
Labels: Feature✨

#1021 2.0 Add [br] modifier text command
  addons/dialogic/Events/Text/Display_DialogText.gd
Labels: Feature✨

#1023 2.0 Improve Resource Picker
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.gd
  addons/dialogic/Editor/Events/Fields/DialogicResourcePicker.tscn
  addons/dialogic/Editor/Events/styles/InputFieldsStyle.tres
  addons/dialogic/Events/Character/PortraitSettings.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Jump/event.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd
  addons/dialogic/Events/Text/Settings_DialogText.gd
  addons/dialogic/Events/Text/event.gd
Labels: Noob Friendly 👍, UI/UX ✏

#1032 2.0 Set Variable Improvements
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.tscn
  addons/dialogic/Editor/Events/Fields/OptionSelector.gd
  addons/dialogic/Editor/Events/Fields/OptionSelector.tscn
  addons/dialogic/Editor/Events/Fields/SinglelineText.tscn
  addons/dialogic/Editor/Events/Fields/Text.gd
  addons/dialogic/Events/Character/PortraitSettings.tscn
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Jump/event.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.tscn
  addons/dialogic/Events/Text/Settings_DialogText.gd
  addons/dialogic/Events/Text/Settings_DialogText.tscn
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Events/Variable/Subsystem_Variables.gd
  addons/dialogic/Events/Variable/event.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨, UI/UX ✏

#1035 2.0 Editor Improvements
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
  addons/dialogic/Editor/Common/Toolbar.gd
  addons/dialogic/Editor/Common/Toolbar.tscn
  addons/dialogic/Editor/EditorView.gd
  addons/dialogic/Editor/EditorView.tscn
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/EventNode/EventNode.tscn
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
  addons/dialogic/Events/Call Node/event.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Choice/event.gd
  addons/dialogic/Events/Jump/event.gd
  addons/dialogic/Events/Music/event.gd
  addons/dialogic/Events/Sound/event.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd
  addons/dialogic/Events/Text/Settings_DialogText.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Events/Variable/event.gd
Labels: UI/UX ✏

#1037 2.0 Create better default/example dialog nodes
  addons/dialogic/Editor/Settings/SettingsEditor.tscn
  addons/dialogic/Editor/Settings/Settings_General.gd
  addons/dialogic/Editor/Settings/Settings_General.tscn
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Text/Display_DialogText.gd
  addons/dialogic/Events/Text/Display_NameLabel.gd
  addons/dialogic/Events/Text/Subsystem_Text.gd
  addons/dialogic/Example Assets/backgrounds/BubbleEnd.png
  addons/dialogic/Example Assets/backgrounds/rpg_box.webp
  addons/dialogic/Example Assets/portraits/Portrait1.png
  addons/dialogic/Example Assets/portraits/Portrait2.png
  addons/dialogic/Example Assets/portraits/rpg_portraits/base1.png
  addons/dialogic/Example Assets/portraits/rpg_portraits/base2.png
  addons/dialogic/Example Assets/portraits/rpg_portraits/base3.png
  addons/dialogic/Example Assets/portraits/rpg_portraits/base4.png
  addons/dialogic/Other/DefaultDialogNode.tscn
  addons/dialogic/Other/ExampleTextBubble.gd
  addons/dialogic/Other/HideWithChild.gd
  addons/dialogic/Other/RPG_BigCharacterDialogNode.tscn
  addons/dialogic/Other/RPG_DialogNode.tscn
  addons/dialogic/Other/TestTimelineScene.gd
  addons/dialogic/Other/TestTimelineScene.tscn
  addons/dialogic/Other/TextBubble_DialogNode.tscn
Labels: Feature✨, Noob Friendly 👍

#1057 Small Event UI improvements
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/EventNode/EventNode.tscn
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.tscn
  addons/dialogic/Editor/Events/Fields/MultilineText.tscn
  addons/dialogic/plugin.gd
Labels: UI/UX ✏

#1060 Many Event Logic and Visual improvements
  addons/dialogic/Editor/Events/BranchEnd.gd
  addons/dialogic/Editor/Events/BranchEnd.tscn
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/EventNode/EventNode.tscn
  addons/dialogic/Editor/Events/Fields/Array.gd
  addons/dialogic/Editor/Events/Fields/Array.tscn
  addons/dialogic/Editor/Events/Fields/MultilineText.tscn
  addons/dialogic/Editor/TimelineEditor/TimelineArea.gd
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.tscn
  addons/dialogic/Events/Choice/Choice_End.gd
  addons/dialogic/Events/Choice/Choice_End.tscn
  addons/dialogic/Events/Choice/Subsystem_Choices.gd
  addons/dialogic/Events/Choice/event.gd
  addons/dialogic/Events/Condition/Condition_End.gd
  addons/dialogic/Events/Condition/Condition_End.tscn
  addons/dialogic/Events/Condition/event.gd
  addons/dialogic/Events/End Branch/event.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Resources/TimelineResourceLoader.gd
  addons/dialogic/Resources/TimelineResourceSaver.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨, UI/UX ✏
