Repository dialogic-godot/dialogic, pull requests merged in 2022-01, with the labels that each got.

#699 Fix Definition Portraits
  addons/dialogic/Nodes/DialogNode.gd
Labels: Bug 🐞

#697 Fix TextBubble BBCode/Tag Regex
  addons/dialogic/Nodes/TextBubble.gd
Labels: Bug 🐞, Critical 💩

#716 Add check for correct text length
  addons/dialogic/Nodes/TextBubble.gd
Labels: Bug 🐞

#718 Fix signal connection delay
  addons/dialogic/Nodes/canvas_dialog_node.gd
Labels: Bug 🐞

#724 Make sure timeline editor load adds all events at the end
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
Labels: Bug 🐞, Critical 💩

#722 Update so Mac-hotkeys work
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
Labels: Bug 🐞

#728 Documentation and MarkdownParser update
  addons/dialogic/Documentation/Content/Changelog.md
  addons/dialogic/Documentation/Content/Reference/Character.md
  addons/dialogic/Documentation/Content/Reference/Theme.md
  addons/dialogic/Documentation/Nodes/DocsMarkdownParser.gd
Labels: Bug 🐞, Documentation 📚

#732 Removed obsolete line
  addons/dialogic/Editor/SettingsEditor/SettingsEditor.gd
Labels: Bug 🐞

#741 Disable shortcut in choice button tooltip
  addons/dialogic/Nodes/DialogNode.gd
Labels: Bug 🐞

#742 Animation and z_index for the Character Join Event
  addons/dialogic/Editor/Events/CharacterJoin.tscn
  addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/CharacterJoinSettings.tscn
  addons/dialogic/Editor/Events/Parts/ResourcePickers/Characters/EventPart_CharacterJoinSettings.gd
  addons/dialogic/Nodes/DialogNode.gd
  addons/dialogic/Nodes/Portrait.gd
  addons/dialogic/Nodes/Portrait.tscn
  addons/dialogic/Other/DialogicUtil.gd
Labels: Improvement✨

#745 Add option that toggles if portraits are behind or on top of text box
  addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
  addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
  addons/dialogic/Nodes/DialogNode.gd
Labels: Improvement✨

#753 Fixes for different things
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
  addons/dialogic/Editor/MasterTree/MasterTree.gd
  addons/dialogic/Nodes/Background.gd
  addons/dialogic/Nodes/DialogNode.gd
  addons/dialogic/Nodes/TextBubble.gd
Labels: Bug 🐞, Improvement✨, UI/UX ✏
