Repository dialogic-godot/dialogic, pull requests merged in 2022-08, with the labels that each got.

#1073 Add default portrait and mood
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.tscn
  addons/dialogic/Events/Text/DialogicDisplay_TypeSounds.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Resources/character.gd
  characters/Emilio.dch
  characters/Jowan.dch
Labels: Feature✨

#1077 Event UI updates
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/EventNode/EventNode.tscn
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.tscn
  addons/dialogic/Editor/Events/Fields/ConditionPicker.gd
  addons/dialogic/Editor/Events/Fields/ConditionPicker.tscn
  addons/dialogic/Editor/Events/Fields/FilePicker.gd
  addons/dialogic/Editor/Events/Fields/SinglelineText.tscn
  addons/dialogic/Editor/Events/Fields/Text.gd
  addons/dialogic/Events/Call Node/event.gd
  addons/dialogic/Events/Voice/event.gd
Labels: UI/UX ✏

#1079 QuickFix for ConditionPicker
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/Events/Fields/ConditionPicker.gd
  addons/dialogic/Editor/Events/Fields/ConditionPicker.tscn
  addons/dialogic/Editor/Events/Fields/OptionSelector.gd
Labels: Bug 🐞

#1081 Small fixes
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
  addons/dialogic/Events/Choice/event.gd
  addons/dialogic/Events/Text/Subsystem_Text.gd
  addons/dialogic/Events/Text/event.gd
Labels: Bug 🐞, UI/UX ✏

#1083 Fix TimelineLoader
  addons/dialogic/Resources/TimelineResourceLoader.gd
Labels: Bug 🐞

#1085 Add dependency updates when moving files in godot
  addons/dialogic/Resources/CharacterResourceLoader.gd
  addons/dialogic/Resources/TimelineResourceLoader.gd
Labels: Feature✨

#1096 More runtime speed improvements
  addons/dialogic/Events/Jump/event.gd
  addons/dialogic/Events/Save/Subsystem_Save.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Resources/event.gd
Labels: Bug 🐞

#1099 2.0 Additional Background Options
  addons/dialogic/Events/Background/Display_Background.gd
  addons/dialogic/Events/Background/Subsystem_Backgrounds.gd
  addons/dialogic/Events/Background/event.gd
Labels: Feature✨

#1105 Fix Event Lines if Timeline ends with Question
  addons/dialogic/Editor/Common/Toolbar.gd
  addons/dialogic/Editor/TimelineEditor/TimelineArea.gd
Labels: UI/UX ✏

#1111 Add glossary
  addons/dialogic/Events/Glossary/GlossaryResource.gd
  addons/dialogic/Events/Glossary/SettingsEditor/Editor.tscn
  addons/dialogic/Events/Glossary/SettingsEditor/GlossaryEditor.gd
  addons/dialogic/Events/Glossary/Subsystem_Glossary.gd
  addons/dialogic/Events/Glossary/definition.svg
  addons/dialogic/Events/Glossary/event.gd
  addons/dialogic/Events/Glossary/icon.png
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Example Assets/ExampleScenes/DefaultDialogNode.gd
  addons/dialogic/Example Assets/ExampleScenes/DefaultDialogNode.tscn
  addons/dialogic/Example Assets/ExampleScenes/ExampleGlossaryPopup.gd
  addons/dialogic/Example Assets/ExampleScenes/ExampleTextBubble.gd
  addons/dialogic/Example Assets/ExampleScenes/HideWithChild.gd
  addons/dialogic/Example Assets/ExampleScenes/RPG_BigCharacterDialogNode.tscn
  addons/dialogic/Example Assets/ExampleScenes/RPG_DialogNode.tscn
  addons/dialogic/Example Assets/ExampleScenes/TextBubble_DialogNode.tscn
  addons/dialogic/Other/TestTimelineScene.gd
Labels: Feature✨

#1122 Add pause() and resume() methods
  addons/dialogic/Events/Character/DefaultAnimations/bounce_in.gd
  addons/dialogic/Events/Character/DefaultAnimations/bounce_out.gd
  addons/dialogic/Events/Character/DefaultAnimations/fade_in_up.gd
  addons/dialogic/Events/Character/DefaultAnimations/fade_out_down.gd
  addons/dialogic/Events/Character/DefaultAnimations/heartbeat.gd
  addons/dialogic/Events/Character/DefaultAnimations/tada.gd
  addons/dialogic/Events/Character/DialogicAnimationClass.gd
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Choice/Subsystem_Choices.gd
  addons/dialogic/Events/Music/Subsystem_Audio.gd
  addons/dialogic/Events/Text/DialogicDisplay_TypeSounds.gd
  addons/dialogic/Events/Text/Display_DialogText.gd
  addons/dialogic/Events/Text/Display_InputHandler.gd
  addons/dialogic/Events/Text/Subsystem_Text.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Events/Voice/Subsystem_Voice.gd
  addons/dialogic/Events/Voice/event.gd
  addons/dialogic/Other/DefaultPortrait.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/TestTimelineScene.gd
  addons/dialogic/Other/TestTimelineScene.tscn
Labels: Feature✨

#1130 Add next indicator node and functionality
  addons/dialogic/Events/Text/Display_InputHandler.gd
  addons/dialogic/Events/Text/Display_NextIndicator.gd
  addons/dialogic/Events/Text/Subsystem_Text.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Example Assets/ExampleScenes/DefaultDialogNode.tscn
  addons/dialogic/Example Assets/next-indicator/next-indicator.png
Labels: Feature✨

#1129 Separate text-to-events logic
  addons/dialogic/Editor/Common/Toolbar.gd
  addons/dialogic/Editor/EditorView.gd
  addons/dialogic/Editor/Settings/Translations.tscn
  addons/dialogic/Editor/TextEditor/TextEditor.gd
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.gd
  addons/dialogic/Other/TimelineUtil.gd
  addons/dialogic/Resources/TimelineResourceLoader.gd
  addons/dialogic/Resources/TimelineResourceSaver.gd
Labels: Feature✨

#1124 Portrait Position Overhaul
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/Fields/OptionSelector.gd
  addons/dialogic/Editor/Events/Fields/OptionSelector.tscn
  addons/dialogic/Editor/Events/Fields/Vector2.gd
  addons/dialogic/Editor/Events/Fields/Vector2.tscn
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Position/event.gd
  addons/dialogic/Events/Position/icon.png
  addons/dialogic/Other/DefaultPortrait.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨

#1135 Small fixes
  README.md
  addons/dialogic/Editor/TextEditor/TextEditor.gd
  addons/dialogic/Editor/TextEditor/TextEditor.tscn
Labels: Noob Friendly 👍, UI/UX ✏

#1144 Add TextInput event
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/EventNode/EventNode.tscn
  addons/dialogic/Editor/Events/Fields/SinglelineText.gd
  addons/dialogic/Editor/Events/Fields/SinglelineText.tscn
  addons/dialogic/Events/TextInput/DialogicDisplay_TextInput.gd
  addons/dialogic/Events/TextInput/Subsystem_TextInput.gd
  addons/dialogic/Events/TextInput/event.gd
  addons/dialogic/Events/TextInput/icon.png
  addons/dialogic/Example Assets/ExampleScenes/DefaultDialogNode.tscn
Labels: Feature✨

#1145 Allow variables in character display name.
  addons/dialogic/Events/Text/Subsystem_Text.gd
Labels: Feature✨

#1154 Remove Character.name property
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Resources/character.gd
Labels: Noob Friendly 👍, UI/UX ✏

#1157 Fix character name getting lost
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Resources/character.gd
Labels: Bug 🐞, Critical 💩

#1159 Remove TLabel and update settings UI
  addons/dialogic/Editor/Common/TLabel.gd
  addons/dialogic/Editor/Common/TLabel.tscn
  addons/dialogic/Editor/Common/TitleBgStylebox.tres
  addons/dialogic/Editor/Settings/SettingsEditor.gd
  addons/dialogic/Editor/Settings/SettingsEditor.tscn
  addons/dialogic/Editor/Settings/Settings_General.tscn
  addons/dialogic/Editor/Settings/Settings_Translations.tscn
  addons/dialogic/Editor/Settings/Translations.tscn
  addons/dialogic/Editor/TimelineEditor/TimelineEditor.tscn
  addons/dialogic/Events/Character/PortraitSettings.tscn
  addons/dialogic/Events/Choice/ChoicesSettings.tscn
  addons/dialogic/Events/Glossary/SettingsEditor/Editor.tscn
  addons/dialogic/Events/Glossary/SettingsEditor/GlossaryEditor.gd
  addons/dialogic/Events/Save/Settings_Saving.tscn
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds_MoodItem.tscn
  addons/dialogic/Events/Text/Settings_DialogText.gd
  addons/dialogic/Events/Text/Settings_DialogText.tscn
  addons/dialogic/Events/Theme/Theme_CharacterEdit.tscn
  addons/dialogic/Events/Variable/SettingsEditor/Editor.tscn
Labels: UI/UX ✏

#1162 Big character editor/custom portraits updates
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.gd
  addons/dialogic/Editor/CharacterEditor/CharacterEditor.tscn
  addons/dialogic/Editor/CharacterEditor/PortraitEntry.gd
  addons/dialogic/Editor/CharacterEditor/PortraitEntry.tscn
  addons/dialogic/Editor/CharacterEditor/PortraitSettings_Image.gd
  addons/dialogic/Editor/CharacterEditor/PortraitSettings_Layout.gd
  addons/dialogic/Editor/CharacterEditor/PortraitSettings_Scene.gd
  addons/dialogic/Editor/Events/Fields/FilePicker.gd
  addons/dialogic/Editor/Events/Fields/FilePicker.tscn
  addons/dialogic/Editor/Settings/SettingsEditor.gd
  addons/dialogic/Events/Character/Subsystem_Portraits.gd
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Text/CharacterEdit_TypingSounds.gd
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Events/Theme/Theme_CharacterEdit.tscn
  addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.gd
  addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.tscn
  addons/dialogic/Example Assets/portraits/CustomPortrait_FaceAtlas.gd
  addons/dialogic/Example Assets/portraits/CustomPortrait_FaceAtlas.tscn
  addons/dialogic/Example Assets/portraits/Princess/anger.png
  addons/dialogic/Example Assets/portraits/Princess/frown.png
  addons/dialogic/Example Assets/portraits/Princess/joy.png
  addons/dialogic/Example Assets/portraits/Princess/neutral.png
  addons/dialogic/Example Assets/portraits/Princess/princess_blank.png
  addons/dialogic/Example Assets/portraits/Princess/shock.png
  addons/dialogic/Example Assets/portraits/Princess/smile.png
  addons/dialogic/Other/DefaultPortrait.gd
  addons/dialogic/Other/DefaultPortrait.tscn
  addons/dialogic/Resources/CharacterResourceLoader.gd
  characters/Emilio.dch
  characters/Jowan.dch
  timelines/Chapter1.dtl
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏

#1165 - added the ability to customize the focus property of a choice button.
  addons/dialogic/Editor/ThemeEditor/ThemeEditor.gd
  addons/dialogic/Editor/ThemeEditor/ThemeEditor.tscn
  addons/dialogic/Nodes/DialogNode.gd
Labels: Feature✨

#1163 [2.0] Further timeline speedups
  addons/dialogic/Editor/Common/Toolbar.gd
  addons/dialogic/Editor/Common/Toolbar.tscn
  addons/dialogic/Editor/EditorView.gd
  addons/dialogic/Editor/EditorView.tscn
  addons/dialogic/Editor/Events/EventNode/EventNode.gd
  addons/dialogic/Editor/Events/EventNode/EventNode.tscn
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/TextEditor/TextEditor.gd
  addons/dialogic/Editor/TextEditor/TextEditor.tscn
  addons/dialogic/Editor/VisualEditor/AddEventButton.gd
  addons/dialogic/Editor/VisualEditor/AddEventButton.tscn
  addons/dialogic/Editor/VisualEditor/EventButton.gd
  addons/dialogic/Editor/VisualEditor/TimelineArea.gd
  addons/dialogic/Editor/VisualEditor/VisualEditor.gd
  addons/dialogic/Editor/VisualEditor/VisualEditor.tscn
  addons/dialogic/Events/Character/event.gd
  addons/dialogic/Events/Converter/Settings_Converter.gd
  addons/dialogic/Events/Converter/icon.png
  addons/dialogic/Events/Text/event.gd
  addons/dialogic/Events/Wait/event.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
  addons/dialogic/Other/TimelineUtil.gd
  addons/dialogic/Resources/TimelineResourceLoader.gd
  addons/dialogic/Resources/TimelineResourceSaver.gd
  addons/dialogic/Resources/event.gd
  addons/dialogic/Resources/timeline.gd
Labels: Critical 💩
