Repository dialogic-godot/dialogic, pull requests merged in 2023-10, with the labels that each got.

#1768 Fix heavy visibility condition
  addons/dialogic/Modules/Text/event_text.gd
Labels: Bug 🐞, Critical 💩

#1763 Multiple small features & fixes
  addons/dialogic/Editor/Events/Fields/FilePicker.gd
  addons/dialogic/Editor/Events/Fields/FilePicker.tscn
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Modules/Background/default_background.gd
  addons/dialogic/Modules/Background/default_background.tscn
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/Choice/subsystem_choices.gd
  addons/dialogic/Modules/Text/index.gd
  addons/dialogic/Modules/Text/node_type_sound.gd
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Bug 🐞, Feature✨

#1772 Allow spaces in jump's Label and Timeline regex
  addons/dialogic/Modules/Jump/event_jump.gd
Labels: Bug 🐞

#1769 Add an "Open Code" right-click option to events
  addons/dialogic/Editor/Events/EventBlock/event_right_click_menu.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Feature✨, UI/UX ✏

#1756 Clear event
  addons/dialogic/Editor/Events/Fields/BoolButton.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/event_portrait_position.svg
  addons/dialogic/Modules/Character/event_portrait_position.svg.import
  addons/dialogic/Modules/Character/event_position.gd
  addons/dialogic/Modules/Character/update_position.svg.2023_09_23_08_37_47.0.svg
  addons/dialogic/Modules/Character/update_position.svg.2023_09_23_08_37_47.0.svg.import
  addons/dialogic/Modules/Choice/icon.svg
  addons/dialogic/Modules/Clear/clear_background.svg
  addons/dialogic/Modules/Clear/clear_background.svg.import
  addons/dialogic/Modules/Clear/clear_characters.svg
  addons/dialogic/Modules/Clear/clear_characters.svg.import
  addons/dialogic/Modules/Clear/clear_music.svg
  addons/dialogic/Modules/Clear/clear_music.svg.import
  addons/dialogic/Modules/Clear/clear_positions.svg
  addons/dialogic/Modules/Clear/clear_positions.svg.import
  addons/dialogic/Modules/Clear/clear_style.svg
  addons/dialogic/Modules/Clear/clear_style.svg.import
  addons/dialogic/Modules/Clear/event_clear.gd
  addons/dialogic/Modules/Clear/icon.png
  addons/dialogic/Modules/Clear/icon.png.import
  addons/dialogic/Modules/Clear/index.gd
  addons/dialogic/Modules/Condition/icon.svg
  addons/dialogic/Modules/History/icon.svg
  addons/dialogic/Modules/Jump/icon_return.svg
  addons/dialogic/Modules/Save/icon.svg
  addons/dialogic/Modules/Settings/icon.svg
  addons/dialogic/Modules/WaitInput/icon.svg
Labels: Feature✨

#1787 Very small fixes for choices and block movement
  addons/dialogic/Editor/TimelineEditor/VisualEditor/TimelineArea.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Bug 🐞, UI/UX ✏

#1789 Add sound effect settings to default layout
  addons/dialogic/Editor/Events/Fields/FilePicker.gd
  addons/dialogic/Editor/Events/Fields/FilePicker.tscn
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/Text/node_type_sound.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏

#1790 Fix portrait animation pausing and signal error
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Text/event_text.gd
Labels: Bug 🐞

#1795 Make speaker portrait react to [portrait] effect
  addons/dialogic/Modules/Character/subsystem_portraits.gd
Labels: Bug 🐞

#1793 Make sure connect_to_change is only called on actual changes
  addons/dialogic/Modules/Settings/subsystem_settings.gd
Labels: Bug 🐞

#1797 Add dedicated text-event syntax highlighter
  addons/dialogic/Editor/Events/Fields/MultilineText.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
Labels: Bug 🐞, UI/UX ✏

#1761 Fix: Change Style (to different layout scene) breaks
  addons/dialogic/Modules/Audio/subsystem_audio.gd
  addons/dialogic/Modules/Background/subsystem_backgrounds.gd
  addons/dialogic/Modules/Character/node_portrait_container.gd
  addons/dialogic/Modules/Character/preview_character.tres
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/DialogicRPGLayout.tscn
  addons/dialogic/Modules/Jump/subsystem_jump.gd
  addons/dialogic/Modules/Style/event_style.gd
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/Variable/subsystem_variables.gd
  addons/dialogic/Other/Dialogic_Subsystem.gd
Labels: Bug 🐞, Critical 💩

#1800 Fix another export problem
  addons/dialogic/Other/DialogicUtil.gd
Labels: Bug 🐞, Critical 💩

#1755 Extend Auto-Advance
  addons/dialogic/Modules/Settings/subsystem_settings.gd
  addons/dialogic/Modules/Text/default_input_handler.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Feature✨

#1803 Implement Version Checker and Downloader
  addons/dialogic/Editor/Common/side_bar.tscn
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Editor/Common/update_install_window.gd
  addons/dialogic/Editor/Common/update_install_window.tscn
  addons/dialogic/Editor/Common/update_manager.gd
  addons/dialogic/Editor/HomePage/home_page.tscn
  addons/dialogic/Editor/editor_main.gd
  addons/dialogic/Editor/editor_main.tscn
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏

#1825 Add custom MultilineText sizing logic to prevent crash
  addons/dialogic/Editor/Events/Fields/MultilineText.gd
  addons/dialogic/Editor/Events/Fields/MultilineText.tscn
Labels: Bug 🐞

#1847 Update Wiki links on Homepage
  addons/dialogic/Editor/HomePage/home_page.tscn
Labels: UI/UX ✏

#1848 Fixes for TypingSounds
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_type_sound.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Bug 🐞

#1840 Allow listing variables and folders inside of variable folders
  addons/dialogic/Modules/Variable/subsystem_variables.gd
Labels: Feature✨, Noob Friendly 👍
