Repository dialogic-godot/dialogic, pull requests merged in 2023-11, with the labels that each got.

#1857 Improvements to get_variable and set_variable
  addons/dialogic/Modules/Variable/subsystem_variables.gd
Labels: Feature✨

#1812 Add Auto-Skip
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.tscn
  addons/dialogic/Modules/Background/event_background.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/event_position.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/Clear/event_clear.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/DefaultLayouts/Default/animations.gd
  addons/dialogic/Modules/History/subsystem_history.gd
  addons/dialogic/Modules/Text/auto_skip.gd
  addons/dialogic/Modules/Text/default_input_handler.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/node_type_sound.gd
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/TextInput/event_text_input.gd
  addons/dialogic/Modules/Voice/event_voice.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
  addons/dialogic/Other/DialogicGameHandler.gd
Labels: Feature✨, Approved

#1858 Events: New call event
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/Fields/Array.gd
  addons/dialogic/Editor/Events/Fields/Array.tscn
  addons/dialogic/Editor/Events/Fields/ArrayValue.gd
  addons/dialogic/Editor/Events/Fields/ArrayValue.tscn
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Modules/Call/event_call.gd
  addons/dialogic/Modules/Call/icon.png
  addons/dialogic/Modules/Call/icon.png.import
  addons/dialogic/Modules/Call/index.gd
  addons/dialogic/Modules/CallNode/event_call_node.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏, Events

#1822 Standalone Input subsystem & InputNode
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Modules/Background/event_background.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/event_position.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Choice/subsystem_choices.gd
  addons/dialogic/Modules/Clear/event_clear.gd
  addons/dialogic/Modules/Core/index.gd
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/DefaultLayouts/Default/animations.gd
  addons/dialogic/Modules/DefaultLayouts/Default/autoadvance_indicator.gd
  addons/dialogic/Modules/Save/subsystem_save.gd
  addons/dialogic/Modules/Text/auto_advance.gd
  addons/dialogic/Modules/Text/auto_skip.gd
  addons/dialogic/Modules/Text/default_input_handler.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/index.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/node_input.gd
  addons/dialogic/Modules/Text/node_type_sound.gd
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/TextInput/event_text_input.gd
  addons/dialogic/Modules/Voice/event_voice.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
Labels: Feature✨, UI/UX ✏

#1864 Multiple fixes: Saving, Layouts, TypeSounds
  addons/dialogic/Editor/Common/update_install_window.gd
  addons/dialogic/Editor/Common/update_install_window.tscn
  addons/dialogic/Editor/Settings/settings_editor.gd
  addons/dialogic/Editor/Settings/settings_page.gd
  addons/dialogic/Editor/editor_main.gd
  addons/dialogic/Editor/editors_manager.gd
  addons/dialogic/Modules/Background/subsystem_backgrounds.gd
  addons/dialogic/Modules/Core/subsystem_expression.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/Style/event_style.gd
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Modules/Text/node_type_sound.gd
  addons/dialogic/Modules/Variable/subsystem_variables.gd
  addons/dialogic/Other/DialogicGameHandler.gd
Labels: Bug 🐞, Critical 💩

#1866 Small fix to handle_event in DialogGameHandler
  addons/dialogic/Other/DialogicGameHandler.gd
Labels: Bug 🐞

#1886 Multiple improvements/fixes
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Editor/Common/update_install_window.tscn
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
  addons/dialogic/Editor/dialogic_editor.gd
  addons/dialogic/Editor/editors_manager.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Bug 🐞, Noob Friendly 👍, UI/UX ✏, Critical 💩

#1839 Fix background bleeding through
  addons/dialogic/Modules/Background/default_background.gd
  addons/dialogic/Modules/Background/default_background.tscn
  addons/dialogic/Modules/Background/default_background_transition.gdshader
  addons/dialogic/Modules/Background/default_background_transition.tres
  addons/dialogic/Modules/Background/dialogic_background.gd
  addons/dialogic/Modules/Background/node_background_holder.gd
  addons/dialogic/Modules/Background/subsystem_backgrounds.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
Labels: Bug 🐞, Feature✨, Needs testing

#1893 Pre-Alpha-11-Adjustments
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/plugin.cfg
Labels: Bug 🐞, Feature✨

#1905 Fix portrait mirror & [portrait] effect
  addons/dialogic/Modules/Character/subsystem_portraits.gd
Labels: Bug 🐞
