Repository dialogic-godot/dialogic, pull requests merged in 2023-08, with the labels that each got.

#1659 Clear text state when hiding textboxes
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
Labels: Bug 🐞, Critical 💩

#1658 Prevent crash when accessing freed layout scene
  addons/dialogic/Other/DialogicGameHandler.gd
Labels: Bug 🐞, Critical 💩

#1660 Rework jump+label+return system
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Editor/Events/Fields/MultilineText.gd
  addons/dialogic/Editor/Events/Fields/MultilineText.tscn
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/directory_holder.gd
  addons/dialogic/Modules/Jump/event_jump.gd
  addons/dialogic/Modules/Jump/event_label.gd
  addons/dialogic/Modules/Jump/event_return.gd
  addons/dialogic/Modules/Jump/index.gd
  addons/dialogic/Modules/Jump/subsystem_jump.gd
  addons/dialogic/Resources/timeline.gd
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏

#1662 Make custom animations part of the module system
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/index.gd
  addons/dialogic/Modules/Character/settings_portraits.gd
  addons/dialogic/Modules/Character/settings_portraits.tscn
  addons/dialogic/Other/DialogicUtil.gd
  addons/dialogic/Other/index_class.gd
Labels: Feature✨

#1664 Further UI changes (timeline editors)
  addons/dialogic/Editor/Events/BranchEnd.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.tscn
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.tscn
  addons/dialogic/Editor/Events/Fields/ConditionPicker.gd
  addons/dialogic/Editor/Events/Fields/ConditionPicker.tscn
  addons/dialogic/Editor/Events/Fields/FilePicker.gd
  addons/dialogic/Editor/Events/Fields/FilePicker.tscn
  addons/dialogic/Editor/Events/Fields/MultilineText.tscn
  addons/dialogic/Editor/Events/Fields/Number.gd
  addons/dialogic/Editor/Events/Fields/Number.tscn
  addons/dialogic/Editor/Events/Fields/OptionSelector.gd
  addons/dialogic/Editor/Events/Fields/OptionSelector.tscn
  addons/dialogic/Editor/Events/Fields/SinglelineText.gd
  addons/dialogic/Editor/Events/Fields/SinglelineText.tscn
  addons/dialogic/Editor/Events/styles/TextBackground.tres
  addons/dialogic/Editor/Events/styles/selected_styleboxflat.tres
  addons/dialogic/Editor/Images/Pieces/variable.svg
  addons/dialogic/Editor/Images/Pieces/variable.svg.import
  addons/dialogic/Editor/Images/Pieces/variable_icon.png
  addons/dialogic/Editor/Images/Pieces/variable_icon.png.import
  addons/dialogic/Editor/Images/Resources/icon_character.png
  addons/dialogic/Editor/Images/Resources/icon_character.png.import
  addons/dialogic/Editor/Settings/settings_general.gd
  addons/dialogic/Editor/Settings/settings_general.tscn
  addons/dialogic/Editor/Settings/settings_modules.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
  addons/dialogic/Editor/directory_holder.gd
  addons/dialogic/Editor/editor_main.gd
  addons/dialogic/Modules/Audio/event_sound.gd
  addons/dialogic/Modules/Background/event_background.gd
  addons/dialogic/Modules/CallNode/event_call_node.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/event_position.gd
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/Choice/ui_choice_end.gd
  addons/dialogic/Modules/Condition/event_condition.gd
  addons/dialogic/Modules/Core/event_end_branch.gd
  addons/dialogic/Modules/End/event_end.gd
  addons/dialogic/Modules/Jump/event_jump.gd
  addons/dialogic/Modules/Jump/event_label.gd
  addons/dialogic/Modules/Jump/event_return.gd
  addons/dialogic/Modules/Save/event_save.gd
  addons/dialogic/Modules/Signal/event_signal.gd
  addons/dialogic/Modules/Style/event_style.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
  addons/dialogic/Modules/TextInput/event_text_input.gd
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/Modules/Voice/event_voice.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
  addons/dialogic/Other/DialogicUtil.gd
  addons/dialogic/Resources/timeline.gd
Labels: UI/UX ✏, Proposal

#1667 Add shortcuts
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/Settings/settings_translation.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Text/event_text.gd
Labels: Feature✨, UI/UX ✏

#1672 Fixed variables hyphen symbol issue #1634
  addons/dialogic/Modules/Variable/variables_editor/variable_field.gd
  addons/dialogic/Modules/Variable/variables_editor/variable_group.gd
Labels: Bug 🐞

#1670 Add new animations
  addons/dialogic/Modules/Character/DefaultAnimations/bounce.gd
  addons/dialogic/Modules/Character/DefaultAnimations/bounce_in.gd
  addons/dialogic/Modules/Character/DefaultAnimations/bounce_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/fade_in_up.gd
  addons/dialogic/Modules/Character/DefaultAnimations/fade_out_down.gd
  addons/dialogic/Modules/Character/DefaultAnimations/heartbeat.gd
  addons/dialogic/Modules/Character/DefaultAnimations/shake_x.gd
  addons/dialogic/Modules/Character/DefaultAnimations/shake_y.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_down.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_left.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_right.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_up.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_down.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_left.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_right.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_up.gd
  addons/dialogic/Modules/Character/DefaultAnimations/tada.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_in.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_in_center.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_out_center.gd
  addons/dialogic/Modules/Character/event_character.gd
Labels: Feature✨

#1678 Add code completion for character event shortcodes
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Modules/Audio/event_music.gd
  addons/dialogic/Modules/Audio/event_sound.gd
  addons/dialogic/Modules/CallNode/event_call_node.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/index.gd
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/Comment/event_comment.gd
  addons/dialogic/Modules/Condition/event_condition.gd
  addons/dialogic/Modules/Jump/event_jump.gd
  addons/dialogic/Modules/Jump/event_label.gd
  addons/dialogic/Modules/Jump/event_return.gd
  addons/dialogic/Modules/Settings/event_setting.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/index.gd
  addons/dialogic/Modules/TextInput/event_text_input.gd
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏

#1677 Remove fit_content_height from Description TextEdit to prevent crash
  addons/dialogic/Editor/CharacterEditor/char_edit_section_general.tscn
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
Labels: Bug 🐞

#1685 Huge layout/style update
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Editor/editor_main.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/DefaultLayouts/Default/ExampleGlossaryPopup.gd
  addons/dialogic/Modules/DefaultLayouts/Default/animations.gd
  addons/dialogic/Modules/DefaultLayouts/Default/autoadvance_indicator.gd
  addons/dialogic/Modules/DefaultLayouts/Default/preview.png
  addons/dialogic/Modules/DefaultLayouts/Default/preview.png.import
  addons/dialogic/Modules/DefaultLayouts/Default/style.cfg
  addons/dialogic/Modules/DefaultLayouts/ExampleHistoryItem.gd
  addons/dialogic/Modules/DefaultLayouts/ExampleHistoryItem.tscn
  addons/dialogic/Modules/DefaultLayouts/ExampleHistoryScene.gd
  addons/dialogic/Modules/DefaultLayouts/ExampleHistoryScene.tscn
  addons/dialogic/Modules/DefaultLayouts/HideWithChild.gd
  addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/DialogicRPGLayout.gd
  addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/DialogicRPGLayout.tscn
  addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/preview.png
  addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/preview.png.import
  addons/dialogic/Modules/DefaultLayouts/RPG_BoxPortrait/style.cfg
  addons/dialogic/Modules/DefaultLayouts/TextBubble/DialogicTextBubbleLayout.gd
  addons/dialogic/Modules/DefaultLayouts/TextBubble/DialogicTextBubbleLayout.tscn
  addons/dialogic/Modules/DefaultLayouts/TextBubble/TextBubble.gd
  addons/dialogic/Modules/DefaultLayouts/TextBubble/TextBubble.tscn
  addons/dialogic/Modules/DefaultLayouts/TextBubble/preview.png
  addons/dialogic/Modules/DefaultLayouts/TextBubble/preview.png.import
  addons/dialogic/Modules/DefaultLayouts/TextBubble/speech_bubble.gdshader
  addons/dialogic/Modules/DefaultLayouts/TextBubble/style.cfg
  addons/dialogic/Modules/DefaultLayouts/index.gd
  addons/dialogic/Modules/LayoutEditor/Components/StyleItem.gd
  addons/dialogic/Modules/LayoutEditor/Components/StyleItem.tscn
  addons/dialogic/Modules/LayoutEditor/Components/StyleList.gd
  addons/dialogic/Modules/LayoutEditor/Components/StyleList.tscn
  addons/dialogic/Modules/LayoutEditor/Components/layout_selection_page.gd
  addons/dialogic/Modules/LayoutEditor/layout_editor.gd
  addons/dialogic/Modules/LayoutEditor/layout_editor.tscn
  addons/dialogic/Modules/Style/character_settings_style.gd
  addons/dialogic/Modules/Style/character_settings_style.tscn
  addons/dialogic/Modules/Style/event_style.gd
  addons/dialogic/Modules/Style/node_style.gd
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Feature✨

#1689 Fix for #1680 and #1616 and #1688
  addons/dialogic/Modules/CallNode/event_call_node.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/DefaultLayouts/Default/ExampleGlossaryPopup.gd
  addons/dialogic/Modules/DefaultLayouts/Default/animations.gd
  addons/dialogic/Modules/DefaultLayouts/Default/autoadvance_indicator.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Bug 🐞, Feature✨

#1690 Fix style list defaults (crash) and character text info
  addons/dialogic/Modules/Style/character_settings_style.gd
  addons/dialogic/Modules/Style/character_settings_style.tscn
  addons/dialogic/Modules/Style/event_style.gd
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Bug 🐞, UI/UX ✏

#1692 More small fixes
  addons/dialogic/Editor/HomePage/home_page.tscn
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/LayoutEditor/layout_editor.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Bug 🐞, Feature✨

#1695 Pre alpha-9 fixes
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Editor/Events/BranchEnd.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.tscn
  addons/dialogic/Editor/HomePage/tips.txt
  addons/dialogic/Editor/Settings/settings_editor.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/LayoutEditor/layout_editor.tscn
  addons/dialogic/plugin.cfg
Labels: Bug 🐞

#1698 Remove invalid symbols from file names before creation
  addons/dialogic/Editor/editors_manager.gd
Labels: Feature✨, Noob Friendly 👍

#1701 Many fixes
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Modules/Character/event_position.gd
  addons/dialogic/Modules/DefaultLayouts/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/DefaultLayouts/HideWithChild.gd
  addons/dialogic/Modules/DefaultLayouts/TextBubble/TextBubble.tscn
  addons/dialogic/Modules/History/event_history.gd
  addons/dialogic/Modules/Settings/event_setting.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_name_label.gd
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/Resources/event.gd
Labels: Bug 🐞, Feature✨, UI/UX ✏, Events

#1697 Make code completion helper and syntax highlighter global
  addons/dialogic/Editor/CharacterEditor/char_edit_p_section_layout.tscn
  addons/dialogic/Editor/CharacterEditor/char_edit_section_general.gd
  addons/dialogic/Editor/Events/Fields/MultilineText.gd
  addons/dialogic/Editor/Events/Fields/MultilineText.tscn
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.tscn
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Editor/editor_main.tscn
Labels: Bug 🐞, Feature✨

#1702 More checks to prevent already freed portraits to cause trouble
  addons/dialogic/Modules/Character/subsystem_portraits.gd
Labels: Bug 🐞
