Repository dialogic-godot/dialogic, pull requests merged in 2023-05, with the labels that each got.

#1543 Fixes for messed up translation paths
  addons/dialogic/Editor/Settings/settings_translation.gd
  addons/dialogic/Events/DefaultStyles/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Other/DialogicUtil.gd
Labels: Bug 🐞

#1545 Some small translation fixes
  addons/dialogic/Editor/Settings/settings_translation.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
Labels: Bug 🐞

#1546 Avoid git changes and remove Dialogic.get_project_setting()
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Editor/Events/EventBlock/event_right_click_menu.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.tscn
  addons/dialogic/Editor/Events/Fields/ConditionPicker.gd
  addons/dialogic/Editor/Events/Fields/FilePicker.gd
  addons/dialogic/Editor/Settings/settings_general.gd
  addons/dialogic/Editor/Settings/settings_modules.gd
  addons/dialogic/Editor/Settings/settings_translation.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
  addons/dialogic/Editor/editors_manager.gd
  addons/dialogic/Events/Character/event_character.gd
  addons/dialogic/Events/Character/settings_portraits.gd
  addons/dialogic/Events/Character/subsystem_portraits.gd
  addons/dialogic/Events/Choice/event_choice.gd
  addons/dialogic/Events/Choice/settings_choices.gd
  addons/dialogic/Events/Choice/subsystem_choices.gd
  addons/dialogic/Events/Glossary/glossary_editor.gd
  addons/dialogic/Events/Glossary/subsystem_glossary.gd
  addons/dialogic/Events/History/settings_history.gd
  addons/dialogic/Events/LayoutEditor/Components/StyleList.gd
  addons/dialogic/Events/LayoutEditor/layout_editor.gd
  addons/dialogic/Events/Save/settings_save.gd
  addons/dialogic/Events/Save/subsystem_save.gd
  addons/dialogic/Events/Text/character_settings/ui_mood_item.gd
  addons/dialogic/Events/Text/default_input_handler.gd
  addons/dialogic/Events/Text/node_dialog_text.gd
  addons/dialogic/Events/Text/settings_text.gd
  addons/dialogic/Events/Text/subsystem_text.gd
  addons/dialogic/Events/TextInput/event_text_input.gd
  addons/dialogic/Events/Variable/event_variable.gd
  addons/dialogic/Events/Variable/subsystem_variables.gd
  addons/dialogic/Events/Variable/variables_editor/variables_editor.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
  addons/dialogic/Resources/event.gd
Labels: Bug 🐞, Noob Friendly 👍, UI/UX ✏

#1548 Rework event dragging and moving
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.tscn
  addons/dialogic/Editor/TimelineEditor/VisualEditor/AddEventButton.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/AddEventButton.tscn
  addons/dialogic/Editor/TimelineEditor/VisualEditor/TimelineArea.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
  addons/dialogic/Events/Text/event_text.gd
Labels: Bug 🐞, Feature✨, UI/UX ✏

#1551 Allow hiding event buttons if not needed
  addons/dialogic/Editor/Settings/settings_modules.gd
  addons/dialogic/Editor/Settings/settings_modules.tscn
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Feature✨, UI/UX ✏

#1559 Fix example portrait animated sprite (#1557
  addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.gd
  addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.tscn
Labels: Bug 🐞, Noob Friendly 👍

#1562 New home screen
  addons/dialogic/Editor/HomePage/home_page.gd
  addons/dialogic/Editor/HomePage/home_page.tscn
  addons/dialogic/Editor/HomePage/home_page_box.gd
  addons/dialogic/Editor/HomePage/home_page_box.tscn
  addons/dialogic/Editor/HomePage/icon_bg.png
  addons/dialogic/Editor/HomePage/icon_bg.png.import
  addons/dialogic/Editor/HomePage/tips.txt
  addons/dialogic/Example Assets/backgrounds/green-field.png
  addons/dialogic/Example Assets/backgrounds/green-field.png.import
  addons/dialogic/Example Assets/backgrounds/vn-background-1.png
  addons/dialogic/Example Assets/backgrounds/vn-background-2.png
  addons/dialogic/Example Assets/backgrounds/vn-background-2.png.import
  addons/dialogic/Example Assets/backgrounds/vn-background-3.png
  addons/dialogic/Example Assets/backgrounds/vn-background-3.png.import
Labels: UI/UX ✏

#1563 Addressing Issue #1552 remove auto-pauses
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
Labels: Noob Friendly 👍, UI/UX ✏

#1568 Make event categories more flexible
  addons/dialogic/Editor/Settings/settings_general.gd
  addons/dialogic/Editor/Settings/settings_general.tscn
  addons/dialogic/Editor/TimelineEditor/VisualEditor/AddEventButton.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
  addons/dialogic/Example Assets/default_event.gd
  addons/dialogic/Modules/Audio/event_music.gd
  addons/dialogic/Modules/Audio/event_sound.gd
  addons/dialogic/Modules/Background/event_background.gd
  addons/dialogic/Modules/CallNode/event_call_node.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/event_position.gd
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/Comment/event_comment.gd
  addons/dialogic/Modules/Condition/event_condition.gd
  addons/dialogic/Modules/Core/event_end_branch.gd
  addons/dialogic/Modules/End/event_end.gd
  addons/dialogic/Modules/Glossary/event_glossary.gd
  addons/dialogic/Modules/History/event_history.gd
  addons/dialogic/Modules/Jump/event_jump.gd
  addons/dialogic/Modules/Jump/event_label.gd
  addons/dialogic/Modules/Save/event_save.gd
  addons/dialogic/Modules/Signal/event_signal.gd
  addons/dialogic/Modules/Style/event_style.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/TextInput/event_text_input.gd
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/Modules/Voice/event_voice.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
  addons/dialogic/Resources/event.gd
Labels: UI/UX ✏

#1570 This makes timeline erasing less likely
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Bug 🐞, Critical 💩

#1571 Change event folding/expanding icon
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.tscn
Labels: Noob Friendly 👍, UI/UX ✏

#1574 Fix version and add argument default
  addons/dialogic/Modules/Save/subsystem_save.gd
  addons/dialogic/plugin.cfg
Labels: Bug 🐞

#1573 Fix issue #1383: Generic autofocus on event creation with button
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/Fields/ComplexPicker.gd
  addons/dialogic/Editor/Events/Fields/MultilineText.gd
  addons/dialogic/Editor/Events/Fields/Number.gd
  addons/dialogic/Editor/Events/Fields/SinglelineText.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/Comment/event_comment.gd
  addons/dialogic/Modules/Jump/event_jump.gd
  addons/dialogic/Modules/Jump/event_label.gd
  addons/dialogic/Modules/Signal/event_signal.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨, UI/UX ✏

#1577 Multiple fixes (portraits, backgrounds, glossary)
  addons/dialogic/Modules/Background/default_background.tscn
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.tscn
Labels: Bug 🐞

#1578 Improve start method
  addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Feature✨

#1576 Some fixes to the converter
  addons/dialogic/Modules/Converter/settings_converter.gd
Labels: Bug 🐞

#1575 Add persistent settings and Settings subsystem/event
  addons/dialogic/Editor/Settings/settings_general.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Settings/event_setting.gd
  addons/dialogic/Modules/Settings/icon.svg
  addons/dialogic/Modules/Settings/icon.svg.import
  addons/dialogic/Modules/Settings/index.gd
  addons/dialogic/Modules/Settings/subsystem_settings.gd
  addons/dialogic/Modules/Text/character_settings/ui_mood_item.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/Resources/event.gd
  addons/dialogic/plugin.gd
Labels: Feature✨

#1579 Improve text systems and TextBubble layout system
  addons/dialogic/Modules/DefaultStyles/TextBubble/DialogicTextBubbleLayout.gd
  addons/dialogic/Modules/DefaultStyles/TextBubble/DialogicTextBubbleLayout.tscn
  addons/dialogic/Modules/DefaultStyles/TextBubble/TextBubble.gd
  addons/dialogic/Modules/DefaultStyles/TextBubble/TextBubble.tscn
  addons/dialogic/Modules/DefaultStyles/TextBubble/speech_bubble.gdshader
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Feature✨

#1580 Expose next indicator settings to default layout customizer
  addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.gd
  addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/LayoutEditor/layout_editor.gd
Labels: Feature✨, UI/UX ✏

#1582 Add Settings to text bubble layout
  addons/dialogic/Modules/DefaultStyles/TextBubble/DialogicTextBubbleLayout.gd
  addons/dialogic/Modules/DefaultStyles/TextBubble/DialogicTextBubbleLayout.tscn
  addons/dialogic/Modules/DefaultStyles/TextBubble/TextBubble.gd
  addons/dialogic/Modules/DefaultStyles/TextBubble/TextBubble.tscn
  addons/dialogic/Modules/DefaultStyles/TextBubble/speech_bubble.gdshader
  addons/dialogic/Modules/LayoutEditor/layout_editor.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: UI/UX ✏

#1584 Improvements to call node event and visual timeline fixes
  addons/dialogic/Editor/Events/BranchEnd.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/Fields/Array.gd
  addons/dialogic/Editor/Events/Fields/Array.tscn
  addons/dialogic/Editor/TimelineEditor/VisualEditor/TimelineArea.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
  addons/dialogic/Modules/CallNode/event_call_node.gd
Labels: Bug 🐞, UI/UX ✏

#1586 Multiple fixes (all over the place)
  addons/dialogic/Editor/Settings/settings_modules.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Modules/Choice/settings_choices.gd
  addons/dialogic/Modules/Choice/settings_choices.tscn
  addons/dialogic/Modules/Choice/subsystem_choices.gd
  addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.gd
  addons/dialogic/Modules/DefaultStyles/Default/DialogicDefaultLayout.tscn
  addons/dialogic/Modules/Text/default_input_handler.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
Labels: Feature✨
