Repository dialogic-godot/dialogic, pull requests merged in 2024-04, with the labels that each got.

#2165 Support `PackedScene` in the Call Event.
  addons/dialogic/Modules/Call/event_call.gd
Labels: Bug 🐞, Enhance ⚡

#2178 Fix use of FileAccess.file_exists()
  addons/dialogic/Core/DialogicResourceUtil.gd
  addons/dialogic/Core/DialogicUtil.gd
  addons/dialogic/Core/index_class.gd
  addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Editor/Settings/csv_file.gd
  addons/dialogic/Editor/Settings/settings_modules.gd
  addons/dialogic/Editor/Settings/settings_translation.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.gd
  addons/dialogic/Modules/Glossary/glossary_editor.gd
  addons/dialogic/Modules/Save/subsystem_save.gd
  addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
  addons/dialogic/Resources/TimelineResourceLoader.gd
  addons/dialogic/Resources/event.gd
Labels: Bug 🐞

#2181 Small fixes
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble.gd
  addons/dialogic/Modules/Save/subsystem_save.gd
  addons/dialogic/Modules/Text/manual_advance.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Bug 🐞

#2184 Fix "timeline info could reset after new timeline was loaded"
  addons/dialogic/Core/DialogicGameHandler.gd
Labels: Bug 🐞

#2182 Add simple context menu to resource sidebar
  addons/dialogic/Editor/Common/side_bar.tscn
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Modules/Variable/variables_editor/variables_editor.gd
Labels: Bug 🐞, UI/UX ✏, Enhance ⚡

#2185 Attempt at improving glossary tag clicking & mouse input logic
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.tscn
  addons/dialogic/Modules/DefaultLayoutParts/Style_VN_Default/default_vn_style.tres
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/node_input.gd
Labels: Bug 🐞, Enhance ⚡

#2186 Make sure we save on exit! + Small Glossary Layer cleanup
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_Glossary/glossary_popup_layer.gd
  addons/dialogic/plugin.gd
Labels: Bug 🐞, Enhance ⚡

#2187 Small improvements
  addons/dialogic/Editor/Events/Fields/field_options_dynamic.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Modules/Text/settings_text.gd
Labels: Bug 🐞

#2189 Input improvements and Text Settings cleanup
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
Labels: Bug 🐞, Feature✨, Enhance ⚡

#2192 Fix autoadvance with delay = 0
  addons/dialogic/Modules/Text/auto_advance.gd
Labels: Bug 🐞

#2204 Remove direct Dialogic reference to avoid installation error
  addons/dialogic/Modules/DefaultLayoutParts/Layer_History/history_layer.gd
Labels: Bug 🐞

#2205 Remove dedundant text height calculation! Hurray!
  addons/dialogic/Editor/Events/Fields/field_text_multiline.gd
  addons/dialogic/Editor/Events/Fields/field_text_multiline.tscn
Labels: Enhance ⚡

#2203 Implement label display name (translatable) & store last label
  addons/dialogic/Modules/Jump/event_label.gd
  addons/dialogic/Modules/Jump/subsystem_jump.gd
  addons/dialogic/Resources/event.gd
Labels: Feature✨, Enhance ⚡

#2201 Allow expressions as portraits
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/CharacterEditor/character_editor_portrait_tree.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Core/subsystem_expression.gd
  addons/dialogic/Modules/Text/event_text.gd
Labels: Feature✨

#2210 Simplify glossary translation code
  addons/dialogic/Editor/Settings/settings_translation.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_Glossary/glossary_popup_layer.gd
  addons/dialogic/Modules/Glossary/glossary_resource.gd
  addons/dialogic/Modules/Glossary/subsystem_glossary.gd
Labels: Enhance ⚡
