Repository dialogic-godot/dialogic, pull requests merged in 2024-03, with the labels that each got.

#2133 Prevent `EditorInterface` breaking Builds
  addons/dialogic/Core/DialogicUtil.gd
  addons/dialogic/Editor/Settings/settings_general.gd
Labels: Bug 🐞

#2128 Add support for Alias Glossary Dictionary Keys
  addons/dialogic/Modules/Glossary/glossary_resource.gd
Labels: Bug 🐞

#2122 Add documentation to the `Background` and `Audio` subsystem
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Modules/Audio/subsystem_audio.gd
  addons/dialogic/Modules/Background/subsystem_backgrounds.gd
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/Save/subsystem_save.gd
  addons/dialogic/Modules/Voice/subsystem_voice.gd
Labels: Documentation 📚, Enhance ⚡

#2141 Fix style editor layer icon size
  addons/dialogic/Modules/DefaultLayoutParts/Layer_History/history_icon.svg
  addons/dialogic/Modules/DefaultLayoutParts/Layer_SpeakerPortraitTextbox/speaker-textbox-icon.svg
  addons/dialogic/Modules/DefaultLayoutParts/Layer_TextInput/text_input_layer_icon.svg
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Portraits/portrait_layer_icon.svg
  addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
Labels: UI/UX ✏

#2137 Improve Choices Script and VN Text Box Layer
  addons/dialogic/Modules/Choice/node_choice_button.gd
  addons/dialogic/Modules/Choice/subsystem_choices.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.gd
Labels: Enhance ⚡

#2146 don't emit `Dialogic.timeline_ended` until `Timeline#clean` has been called
  addons/dialogic/Core/DialogicGameHandler.gd
Labels: Bug 🐞

#2153 Remember the Timeline Sidebar Size
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Enhance ⚡
