Repository dialogic-godot/dialogic, pull requests merged in 2024-05, with the labels that each got.

#2217 Prevent default portrait from spamming error
  addons/dialogic/Modules/Character/subsystem_portraits.gd
Labels: Bug 🐞

#2223 Fix subsystem dependencies bug #2222
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Bug 🐞

#2214 Fix to autoskip and wait event pausing
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/History/subsystem_history.gd
  addons/dialogic/Modules/Wait/event_wait.gd
Labels: Bug 🐞, Enhance ⚡

#2212 Audio event bus management simplification
  addons/dialogic/Modules/Audio/event_music.gd
  addons/dialogic/Modules/Audio/event_sound.gd
  addons/dialogic/Modules/Audio/subsystem_audio.gd
Labels: Enhance ⚡

#2215 Improve the variable_changed signals and their info dictionaries
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/Modules/Variable/subsystem_variables.gd
Labels: Enhance ⚡

#2234 Update TimelineResourceLoader.
  addons/dialogic/Resources/TimelineResourceLoader.gd
Labels: Enhance ⚡

#2235 Update CharacterResourceLoader and CharacterResourceSaver.
  addons/dialogic/Resources/CharacterResourceLoader.gd
  addons/dialogic/Resources/CharacterResourceSaver.gd
Labels: Enhance ⚡

#2239 Use "contrast_color_1" for now
  addons/dialogic/Editor/Common/hint_tooltip_icon.gd
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
Labels: Bug 🐞, UI/UX ✏

#2240 Variable fixes
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/Modules/Variable/variables_editor/variable_tree.gd
Labels: Bug 🐞, UI/UX ✏, Critical 💩

#2237 Field Color for Event
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/Fields/field_color.gd
  addons/dialogic/Editor/Events/Fields/field_color.tscn
  addons/dialogic/Resources/event.gd
Labels: Feature✨, UI/UX ✏

#2241 Small fixes before alpha 14
  addons/dialogic/Modules/Text/manual_advance.gd
  addons/dialogic/Modules/Variable/event_variable.gd
  addons/dialogic/plugin.cfg
Labels: Bug 🐞, Enhance ⚡

#2253 Multiple bug-fixes
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/editors_manager.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble.gd
  addons/dialogic/Modules/Settings/event_setting.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/Variable/variables_editor/variable_tree.gd
  addons/dialogic/plugin.gd
Labels: Bug 🐞

#2119 Add Layered Portraits
  Tests/Unit/guess_special_resource_test.gd
  addons/dialogic/Core/DialogicResourceUtil.gd
  addons/dialogic/Core/DialogicUtil.gd
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/Events/Fields/field_file.gd
  addons/dialogic/Modules/Character/DefaultAnimations/bounce_in.gd
  addons/dialogic/Modules/Character/DefaultAnimations/bounce_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/bounce_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/fade_down_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/fade_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/fade_in_up.gd
  addons/dialogic/Modules/Character/DefaultAnimations/fade_out_down.gd
  addons/dialogic/Modules/Character/DefaultAnimations/fade_up_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/instant_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_down_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_down.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_left.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_right.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_in_up.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_left_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_down.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_left.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_right.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_out_up.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_right_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/slide_up_in.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_center_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_in.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_in_center.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_in_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_out.gd
  addons/dialogic/Modules/Character/DefaultAnimations/zoom_out_center.gd
  addons/dialogic/Modules/Character/LayeredPortrait/layered_portrait.gd
  addons/dialogic/Modules/Character/LayeredPortrait/layered_portrait.tscn
  addons/dialogic/Modules/Character/class_dialogic_animation.gd
  addons/dialogic/Modules/Character/dialogic_portrait.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/settings_portraits.gd
  addons/dialogic/Modules/Character/settings_portraits.tscn
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/StyleEditor/style_editor.tscn
Labels: Feature✨
