Repository dialogic-godot/dialogic, pull requests merged in 2024-10, with the labels that each got.

#2405 Tag dtl and dch files with their resource class
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
  addons/dialogic/Resources/CharacterResourceLoader.gd
  addons/dialogic/Resources/TimelineResourceLoader.gd
Labels: UI/UX ✏, Approved

#2432 handle some null/freed item cases to avoid bugs
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Approved

#2436 Fix test timeline scene error with Dictionary signal event
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
Labels: Bug 🐞, Approved

#2439 Add skippable option to Wait event
  addons/dialogic/Modules/Wait/event_wait.gd
Labels: Approved

#2427 Implement multiple music channels
  addons/dialogic/Modules/Audio/event_music.gd
  addons/dialogic/Modules/Audio/index.gd
  addons/dialogic/Modules/Audio/settings_audio.gd
  addons/dialogic/Modules/Audio/settings_audio.tscn
  addons/dialogic/Modules/Audio/subsystem_audio.gd
  addons/dialogic/Modules/Clear/event_clear.gd
Labels: Approved

#2438 Add text effect for extra_data to Portraits subsystem
  addons/dialogic/Modules/Character/index.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
Labels: Approved

#2441 Fix event fields not reseting
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Jump/event_jump.gd
  addons/dialogic/Modules/Text/event_text.gd
Labels: Approved

#2445 Fix portrait scaling
  addons/dialogic/Modules/Character/subsystem_containers.gd
Labels: Approved

#2402 Styles: Rework internal structure of styles
  addons/dialogic/Modules/Character/node_portrait_container.gd
  addons/dialogic/Modules/DefaultLayoutParts/Style_SpeakerTextbox/speaker_textbox_style.tres
  addons/dialogic/Modules/DefaultLayoutParts/Style_TextBubbles/textbubble_style.tres
  addons/dialogic/Modules/DefaultLayoutParts/Style_VN_Default/default_vn_style.tres
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Modules/StyleEditor/style_editor.gd
  addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
  addons/dialogic/Resources/dialogic_style.gd
  addons/dialogic/Resources/dialogic_style_layer.gd
Labels: Bug 🐞, Enhance ⚡, Compatibility Breaking :warning:

#2442 Fix portrait tree drag drop bugs
  addons/dialogic/Editor/CharacterEditor/character_editor_portrait_tree.gd
Labels: Approved

#2448 Implement audio preview fields
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/Events/Fields/field_audio_preview.gd
  addons/dialogic/Editor/Events/Fields/field_audio_preview.tscn
  addons/dialogic/Modules/Audio/event_music.gd
  addons/dialogic/Modules/Audio/event_sound.gd
  addons/dialogic/Modules/Voice/event_voice.gd
  addons/dialogic/Resources/event.gd
Labels: Needs testing, Approved

#2451 Text Subsystem: Improve autocolor names feature + Choice Subsystem: Allow using input action for choices
  addons/dialogic/Core/DialogicUtil.gd
  addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/Common/update_install_window.gd
  addons/dialogic/Editor/Common/update_manager.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Modules/Audio/subsystem_audio.gd
  addons/dialogic/Modules/Character/default_portrait.gd
  addons/dialogic/Modules/Character/settings_portraits.gd
  addons/dialogic/Modules/Character/subsystem_containers.gd
  addons/dialogic/Modules/Choice/node_choice_button.gd
  addons/dialogic/Modules/Choice/subsystem_choices.gd
  addons/dialogic/Modules/Clear/event_clear.gd
  addons/dialogic/Modules/Core/subsystem_expression.gd
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_Textbubble/text_bubble_layer.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Portraits/vn_portrait_layer.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Feature✨, Enhance ⚡

#2456 TypeSounds: Add a global audio-bus setting
  addons/dialogic/Modules/Audio/settings_audio.gd
  addons/dialogic/Modules/Audio/settings_audio.tscn
  addons/dialogic/Modules/Text/node_type_sound.gd
Labels: Feature✨

#2457 Various pre alpha 16 fixes
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Example Assets/Fonts/Roboto-Bold.ttf.import
  addons/dialogic/Example Assets/Fonts/Roboto-Italic.ttf.import
  addons/dialogic/Example Assets/Fonts/Roboto-Regular.ttf.import
  addons/dialogic/Modules/Audio/settings_audio.tscn
  addons/dialogic/Modules/Audio/subsystem_audio.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Style/subsystem_styles.gd
Labels: Bug 🐞, Critical 💩, Enhance ⚡
