Repository dialogic-godot/dialogic, pull requests merged in 2024-09, with the labels that each got.

#2382 Trim common prefix when importing portraits from folder
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
Labels: Feature✨, UI/UX ✏, Enhance ⚡

#2371 Add inspector field for timelines
  addons/dialogic/Editor/Events/Fields/field_options_dynamic.gd
  addons/dialogic/Editor/Inspector/inspector_plugin.gd
  addons/dialogic/Editor/Inspector/timeline_inspector_field.gd
  addons/dialogic/plugin.gd
Labels: Feature✨, Noob Friendly 👍, UI/UX ✏

#2391 Fix animations not found on export
  addons/dialogic/Core/index_class.gd
Labels: Bug 🐞, Critical 💩

#2387 Fix UID issues on custom style layers
  addons/dialogic/Core/DialogicUtil.gd
  addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd
  addons/dialogic/Modules/StyleEditor/style_editor.gd
  addons/dialogic/Modules/StyleEditor/style_layer_editor.gd
Labels: Bug 🐞, Critical 💩

#2392 Fix debug portraits not showing up
  addons/dialogic/Modules/Character/node_portrait_container.gd
Labels: Bug 🐞

#2395 Styles: Preserve process_mode on style changes
  addons/dialogic/Modules/Style/subsystem_styles.gd
Labels: Feature✨

#2394 Text Editor: Improve CTRL+K commenting behaviour
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
Labels: Bug 🐞, UI/UX ✏

#2393 CharacterEvent: Fix position/size not working correctly when joining
  addons/dialogic/Modules/Character/subsystem_containers.gd
Labels: Bug 🐞, Critical 💩

#2396 Core: More fixes for customizing files (follow up to #2387)
  addons/dialogic/Core/DialogicUtil.gd
Labels: Bug 🐞, Critical 💩

#2350 Sidebar upgrade #1894
  addons/dialogic/Editor/Common/side_bar.tscn
  addons/dialogic/Editor/Common/sidebar.gd
  addons/dialogic/Editor/Images/Pieces/close-icon.svg
  addons/dialogic/Editor/Images/Pieces/close-icon.svg.import
  addons/dialogic/Editor/editor_main.gd
  addons/dialogic/Editor/editor_main.tscn
Labels: UI/UX ✏
