Repository dialogic-godot/dialogic, pull requests merged in 2024-01, with the labels that each got.

#1991 Fix empty-choice-indentation bug
  addons/dialogic/Resources/timeline.gd
Labels: Bug 🐞

#2005 Visual editor improvements
  addons/dialogic/Editor/Events/EventBlock/event_block.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Modules/Background/event_background.gd
Labels: UI/UX ✏

#2006 More BG event adjustments
  addons/dialogic/Modules/Background/event_background.gd
Labels: UI/UX ✏

#2013 Multiple fixes
  addons/dialogic/Editor/Events/BranchEnd.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Modules/DefaultLayoutParts/Base_TextBubble/text_bubble_base.tscn
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Choices/vn_choice_layer.tscn
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.tscn
  addons/dialogic/Resources/character.gd
  addons/dialogic/Resources/timeline.gd
Labels: Bug 🐞, UI/UX ✏

#2019 Ensure characters can be escaped if they begin with event identifiers
  addons/dialogic/Modules/Text/event_text.gd
Labels: Bug 🐞

#2018 Add quick-open to timeline editors
  addons/dialogic/Editor/Events/Fields/field_options_dynamic.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
Labels: Feature✨, UI/UX ✏

#2024 Fix User Input Auto-Advance
  .github/workflows/resources/project.godot
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/Text/auto_advance.gd
  addons/dialogic/Tests/Unit/test_auto_advance.gd
  addons/dialogic/Tests/Unit/test_example.gd
Labels: Bug 🐞

#2025 fix a function bug in subsystem_variables.gd
  addons/dialogic/Modules/Variable/subsystem_variables.gd
Labels: Bug 🐞, Critical 💩

#2020 Extend `DialogicPortrait` by custom portraits.
  addons/dialogic/Example Assets/portraits/CustomPortrait_AnimatedSprite.gd
  addons/dialogic/Example Assets/portraits/CustomPortrait_FaceAtlas.gd
  addons/dialogic/Example Assets/portraits/CustomPortrait_FaceAtlas.tscn
Labels: Bug 🐞

#2030 Move Unit Tests outside of Dialogic
  .github/workflows/unit_test.yml
  Tests/Unit/test_auto_advance.gd
  Tests/Unit/test_example.gd
Labels: Critical 💩, Enhance ⚡

#2027 Improve custom portrait workflow
  addons/dialogic/Editor/CharacterEditor/char_edit_p_section_main.gd
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Example Assets/portraits/simple_highlight_portrait.gd
Labels: UI/UX ✏

#2034 Fix broken plugin name
  addons/dialogic/plugin.gd
Labels: Bug 🐞, Critical 💩

#2039 Remove documentation sections from settings pages
  addons/dialogic/Modules/Save/settings_save.gd
  addons/dialogic/Modules/Save/settings_save.tscn
  addons/dialogic/Modules/Text/settings_text.gd
  addons/dialogic/Modules/Text/settings_text.tscn
Labels: Documentation 📚

#2035 Statically typed subsystems
  Tests/Unit/test_auto_advance.gd
  addons/dialogic/Editor/Settings/settings_general.gd
  addons/dialogic/Editor/Settings/settings_general.tscn
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Modules/Background/event_background.gd
  addons/dialogic/Modules/Call/event_call.gd
  addons/dialogic/Modules/Character/event_character.gd
  addons/dialogic/Modules/Character/event_position.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Choice/subsystem_choices.gd
  addons/dialogic/Modules/Clear/event_clear.gd
  addons/dialogic/Modules/Condition/event_condition.gd
  addons/dialogic/Modules/Core/index.gd
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_Glossary/glossary_popup_layer.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/animations.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/autoadvance_indicator.gd
  addons/dialogic/Modules/Text/auto_advance.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/node_input.gd
  addons/dialogic/Modules/Text/node_type_sound.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/TextInput/event_text_input.gd
  addons/dialogic/Modules/Variable/subsystem_variables.gd
  addons/dialogic/Modules/Voice/event_voice.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
Labels: Feature✨, Critical 💩, Enhance ⚡

#2041 Fix background transitions
  addons/dialogic/Modules/Background/Transitions/class_dialogic_background_transition.gd
  addons/dialogic/Modules/Background/subsystem_backgrounds.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_FullBackground/full_background_layer.tscn
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Portraits/vn_portrait_layer.tscn
Labels: Bug 🐞

#2010 Add Sync Text Reveal to the Playing Voice
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/node_dialog_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Feature✨

#2042 Some method renames and code cleanup
  addons/dialogic/Example Assets/portraits/simple_highlight_portrait.gd
  addons/dialogic/Modules/Audio/subsystem_audio.gd
  addons/dialogic/Modules/Background/subsystem_backgrounds.gd
  addons/dialogic/Modules/Character/subsystem_portraits.gd
  addons/dialogic/Modules/Choice/settings_choices.gd
  addons/dialogic/Modules/Choice/subsystem_choices.gd
  addons/dialogic/Modules/Clear/event_clear.gd
  addons/dialogic/Modules/Core/subsystem_animation.gd
  addons/dialogic/Modules/Core/subsystem_expression.gd
  addons/dialogic/Modules/Core/subsystem_input.gd
  addons/dialogic/Modules/History/subsystem_history.gd
  addons/dialogic/Modules/Jump/subsystem_jump.gd
  addons/dialogic/Modules/Save/subsystem_save.gd
  addons/dialogic/Modules/Settings/subsystem_settings.gd
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Modules/Text/auto_advance.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Modules/TextInput/subsystem_text_input.gd
  addons/dialogic/Modules/Variable/subsystem_variables.gd
  addons/dialogic/Modules/Voice/subsystem_voice.gd
  addons/dialogic/Modules/Wait/event_wait.gd
  addons/dialogic/Modules/WaitInput/event_wait_input.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Other/DialogicUtil.gd
  addons/dialogic/Other/Dialogic_Subsystem.gd
  addons/dialogic/Resources/CharacterResourceLoader.gd
  addons/dialogic/Resources/TimelineResourceLoader.gd
  addons/dialogic/Resources/dialogic_style.gd
  addons/dialogic/Resources/event.gd
Labels: Noob Friendly 👍, Enhance ⚡

#2043 Fix history event
  addons/dialogic/Modules/History/event_history.gd
  addons/dialogic/Modules/History/subsystem_history.gd
Labels: Bug 🐞

#2045 Add sub-Index for mid-text-event loading
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Other/DialogicGameHandler.gd
  addons/dialogic/Resources/timeline.gd
Labels: Feature✨

#2046 Make sure custom portrait is reloaded when portrait scene is saved
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
Labels: UI/UX ✏

#2048 Allow specifying parent to add layout
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Modules/Text/event_text.gd
Labels: Feature✨, Enhance ⚡

#2047 Rename the Other folder to Core
  .github/workflows/resources/project.godot
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Core/DialogicResourceUtil.gd
  addons/dialogic/Core/DialogicUtil.gd
  addons/dialogic/Core/Dialogic_Subsystem.gd
  addons/dialogic/Core/index_class.gd
  addons/dialogic/plugin.gd
Labels: Enhance ⚡
