Repository dialogic-godot/dialogic, pull requests merged in 2024-11, with the labels that each got.

#2470 chore: fix small spelling mistake in event documentation.
  addons/dialogic/Resources/event.gd
Labels: Documentation 📚

#2467 Sort subsystems for cleaner diffs
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Core/DialogicUtil.gd
Labels: Enhance ⚡

#2462 Make visual timeline deselect other items when selecting an already selected one
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Bug 🐞, UI/UX ✏

#2460 Add Character Prefixes and Suffixes to Text Events
  addons/dialogic/Editor/CharacterEditor/character_editor.gd
  addons/dialogic/Editor/CharacterEditor/character_prefix_suffix.gd
  addons/dialogic/Editor/CharacterEditor/character_prefix_suffix.tscn
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Feature✨

#2459 Fix visual editor event copy/paste issues
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Bug 🐞

#2464 fix: portrait overlapping #2458
  addons/dialogic/Modules/Text/event_text.gd
Labels: Bug 🐞

#2486 Fix instancing new Character Nodes on Simple Highlight Portrait
  addons/dialogic/Modules/HighlightPortrait/simple_highlight_portrait.gd
Labels: Bug 🐞
