Repository dialogic-godot/dialogic, pull requests merged in 2024-02, with the labels that each got.

#2071 Fix Current Speaker if nobody speaks
  Tests/Resources/unit_test_character.dch
  Tests/Unit/subsystem_text_test.gd
  addons/dialogic/Modules/Glossary/glossary_editor.tscn
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Enhance ⚡

#2072 Wait one frame before clean to avoid disconnecting internal ONESHOT connections
  addons/dialogic/Core/DialogicGameHandler.gd
Labels: Bug 🐞

#2074 Remove explicit timeline clear to fix #1996
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
Labels: Bug 🐞

#2079 Small fixes
  addons/dialogic/Modules/Background/subsystem_backgrounds.gd
  addons/dialogic/Resources/dialogic_style.gd
Labels: Feature✨, Enhance ⚡

#2101 Fix for broken italics-font setting on default textbox layers
  addons/dialogic/Modules/DefaultLayoutParts/Base_Default/default_layout_base.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_Glossary/glossary_popup_layer.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_History/history_layer.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_SpeakerPortraitTextbox/speaker_portrait_textbox_layer.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Choices/vn_choice_layer.gd
  addons/dialogic/Modules/DefaultLayoutParts/Layer_VN_Textbox/vn_textbox_layer.gd
Labels: Bug 🐞

#2100 Attempt at fixing the timeline clearing mistakes
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Modules/End/event_end.gd
  addons/dialogic/Modules/Style/subsystem_styles.gd
  addons/dialogic/Resources/timeline.gd
Labels: Bug 🐞, Critical 💩

#2103 Improve choice subsystem by exposing most settings
  addons/dialogic/Modules/Choice/event_choice.gd
  addons/dialogic/Modules/Choice/subsystem_choices.gd
Labels: Feature✨, Enhance ⚡

#2110 Improve broken reference manager
  addons/dialogic/Editor/Common/broken_reference_manager.gd
  addons/dialogic/Editor/Common/reference_manager.tscn
  addons/dialogic/Editor/Common/reference_manager_window.gd
Labels: UI/UX ✏

#2108 Show used Locales in Test Locale Dropdown
  addons/dialogic/Editor/Settings/settings_translation.gd
  addons/dialogic/Editor/Settings/settings_translation.tscn
Labels: Enhance ⚡

#2111 Saving-Loading improvements & Other things
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Modules/Audio/subsystem_audio.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
  addons/dialogic/Resources/timeline.gd
Labels: Bug 🐞, Enhance ⚡

#2116 Fix multiline events, improve syntax highlighting and text event height calculation
  addons/dialogic/Editor/Events/Fields/field_text_multiline.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/CodeCompletionHelper.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Resources/timeline.gd
Labels: Bug 🐞, UI/UX ✏, Enhance ⚡

#2117 Small Documentation improvements
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Core/DialogicResourceUtil.gd
  addons/dialogic/Core/DialogicUtil.gd
  addons/dialogic/Resources/dialogic_style.gd
Labels: Documentation 📚, Enhance ⚡

#2083 Add Utility Methods to save Already Seen Events
  Tests/Unit/subsystem_history_test.gd
  addons/dialogic/Example Assets/already_read_indicator.gd
  addons/dialogic/Modules/History/settings_history.gd
  addons/dialogic/Modules/History/settings_history.tscn
  addons/dialogic/Modules/History/subsystem_history.gd
  addons/dialogic/Modules/Save/subsystem_save.gd
  addons/dialogic/Modules/Text/auto_skip.gd
  addons/dialogic/Modules/Text/event_text.gd
Labels: Enhance ⚡
