Repository dialogic-godot/dialogic, pull requests merged in 2025-01, with the labels that each got.

#2479 Styles: Fix persistent info getting lost
  addons/dialogic/Resources/dialogic_layout_base.gd
Labels: Bug 🐞, Enhance ⚡

#2478 Improve random selection regex and highlighting
  addons/dialogic/Editor/TimelineEditor/TextEditor/syntax_highlighter.gd
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Modules/Text/subsystem_text.gd
Labels: Feature✨, Enhance ⚡

#2485 Add Choices to `last_question_info`.
  addons/dialogic/Modules/Choice/subsystem_choices.gd
Labels: Bug 🐞
