Repository dialogic-godot/dialogic, pull requests merged in 2025-02, with the labels that each got.

#2529 Add Timeline Shortcut Cheat Sheet
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Editor/TimelineEditor/shortcut_popup.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.tscn
  addons/dialogic/Editor/editor_main.gd
Labels: UI/UX ✏

#2535 Feature: Play from here
  addons/dialogic/Core/DialogicGameHandler.gd
  addons/dialogic/Editor/Events/EventBlock/event_right_click_menu.gd
  addons/dialogic/Editor/TimelineEditor/TextEditor/timeline_editor_text.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.gd
  addons/dialogic/Editor/TimelineEditor/VisualEditor/timeline_editor_visual.tscn
  addons/dialogic/Editor/TimelineEditor/shortcut_popup.gd
  addons/dialogic/Editor/TimelineEditor/test_timeline_scene.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.gd
  addons/dialogic/Editor/TimelineEditor/timeline_editor.tscn
  addons/dialogic/Modules/Text/event_text.gd
  addons/dialogic/Resources/timeline.gd
Labels: Feature✨

#2421 fix: potential infinite loop on DialogicResourceUtil.gd
  addons/dialogic/Core/DialogicResourceUtil.gd
Labels: Needs testing, Approved
